package units

var (
	ElectricalResistance = UnitOptionQuantity("electrical resistance")

	Ohm      = newUnit("ohm", "Ω", ElectricalResistance, SI)
	DecaOhm  = Deca(Ohm)
	HectoOhm = Hecto(Ohm)
	KiloOhm  = Kilo(Ohm)
	MegaOhm  = Mega(Ohm)
	GigaOhm  = Giga(Ohm)
	TeraOhm  = Tera(Ohm)
	PetaOhm  = Peta(Ohm)
	ExaOhm   = Exa(Ohm)
	ZettaOhm = Zetta(Ohm)
	YottaOhm = Yotta(Ohm)
	DeciOhm  = Deci(Ohm)
	CentiOhm = Centi(Ohm)
	MilliOhm = Milli(Ohm)
	MicroOhm = Micro(Ohm)
	NanoOhm  = Nano(Ohm)
	PicoOhm  = Pico(Ohm)
	FemtoOhm = Femto(Ohm)
	AttoOhm  = Atto(Ohm)
	ZeptoOhm = Zepto(Ohm)
	YoctoOhm = Yocto(Ohm)
)

func init() {
	Ohm.AddSymbols("Ω")
	DecaOhm.AddSymbols("daΩ")
	HectoOhm.AddSymbols("hΩ")
	KiloOhm.AddSymbols("kΩ")
	MegaOhm.AddSymbols("MΩ")
	GigaOhm.AddSymbols("GΩ")
	TeraOhm.AddSymbols("TΩ")
	PetaOhm.AddSymbols("PΩ")
	ExaOhm.AddSymbols("EΩ")
	ZettaOhm.AddSymbols("ZΩ")
	YottaOhm.AddSymbols("YΩ")
	DeciOhm.AddSymbols("dΩ")
	CentiOhm.AddSymbols("cΩ")
	MilliOhm.AddSymbols("mΩ")
	MicroOhm.AddSymbols("µΩ")
	NanoOhm.AddSymbols("nΩ")
	PicoOhm.AddSymbols("pΩ")
	FemtoOhm.AddSymbols("fΩ")
	AttoOhm.AddSymbols("aΩ")
	ZeptoOhm.AddSymbols("zΩ")
	YoctoOhm.AddSymbols("yΩ")
}
