package units

var (
	ElectricalResistance = UnitOptionQuantity("electrical resistance")

	Ohm      = newUnit("ohm", "Ω", ElectricalResistance, SI)
	DecaOhm  = newUnit("decaohm", "daΩ", ElectricalResistance, SI)
	HectoOhm = newUnit("hectoohm", "hΩ", ElectricalResistance, SI)
	KiloOhm  = newUnit("kiloohm", "kΩ", ElectricalResistance, SI)
	MegaOhm  = newUnit("megaohm", "MΩ", ElectricalResistance, SI)
	GigaOhm  = newUnit("gigaohm", "GΩ", ElectricalResistance, SI)
	TeraOhm  = newUnit("teraohm", "TΩ", ElectricalResistance, SI)
	PetaOhm  = newUnit("petaohm", "PΩ", ElectricalResistance, SI)
	ExaOhm   = newUnit("exaohm", "EΩ", ElectricalResistance, SI)
	ZettaOhm = newUnit("zettaohm", "ZΩ", ElectricalResistance, SI)
	YottaOhm = newUnit("yottaohm", "YΩ", ElectricalResistance, SI)
	DeciOhm  = newUnit("deciohm", "dΩ", ElectricalResistance, SI)
	CentiOhm = newUnit("centiohm", "cΩ", ElectricalResistance, SI)
	MilliOhm = newUnit("milliohm", "mΩ", ElectricalResistance, SI)
	MicroOhm = newUnit("microohm", "µΩ", ElectricalResistance, SI)
	NanoOhm  = newUnit("nanoohm", "nΩ", ElectricalResistance, SI)
	PicoOhm  = newUnit("picoohm", "pΩ", ElectricalResistance, SI)
	FemtoOhm = newUnit("femtoohm", "fΩ", ElectricalResistance, SI)
	AttoOhm  = newUnit("attoohm", "aΩ", ElectricalResistance, SI)
	ZeptoOhm = newUnit("zeptoohm", "zΩ", ElectricalResistance, SI)
	YoctoOhm = newUnit("yoctoohm", "yΩ", ElectricalResistance, SI)
)

func init() {
	Ohm.AddSymbols("Ω")
	DecaOhm.AddSymbols("daΩ")
	HectoOhm.AddSymbols("hΩ")
	KiloOhm.AddSymbols("kΩ")
	MegaOhm.AddSymbols("MΩ")
	GigaOhm.AddSymbols("GΩ")
	TeraOhm.AddSymbols("TΩ")
	PetaOhm.AddSymbols("PΩ")
	ExaOhm.AddSymbols("EΩ")
	ZettaOhm.AddSymbols("ZΩ")
	YottaOhm.AddSymbols("YΩ")
	DeciOhm.AddSymbols("dΩ")
	CentiOhm.AddSymbols("cΩ")
	MilliOhm.AddSymbols("mΩ")
	MicroOhm.AddSymbols("µΩ")
	NanoOhm.AddSymbols("nΩ")
	PicoOhm.AddSymbols("pΩ")
	FemtoOhm.AddSymbols("fΩ")
	AttoOhm.AddSymbols("aΩ")
	ZeptoOhm.AddSymbols("zΩ")
	YoctoOhm.AddSymbols("yΩ")
}
